### ISSUE TITLE
Support client certificate authentication for Vault

### ISSUE THREAD

**Issue by wrouesnel** [HeavyHorst/easyKV#3]
Vault supports using client certificates for authentication (i.e. certs authorize and provide a token for further communication). easyKV (and thus Remco) should support this mode.

**Comment by HeavyHorst** [comment]
Youre right. I will probably find some time at the weekend to work on this.

**Comment by HeavyHorst** [comment]
This was easier as expected:

Can you test the pr ?

```go
package main

import (
	"fmt"

	"github.com/HeavyHorst/easyKV/vault"
)

func main() {
	t, err := vault.New("http://127.0.0.1:8200", "cert", vault.WithTLSOptions(vault.TLSOptions{
		ClientCert:   "pathToClientCert",
		ClientKey:    "pathToClientKey",
		ClientCaKeys: "pathToCaKeys",
	}))
	if err != nil {
		panic(err)
	}
	fmt.Println(t.GetValues([]string{"/"}))
}
```

**Comment by HeavyHorst** [comment]
@wrouesnel 
I've created a new remco release where this patch is included. Feel free to test !
