### ISSUE TITLE
File backend flattens arrays

### ISSUE THREAD

**Issue by andreykaipov** [HeavyHorst/easykv#9]
I noticed the file backend parses arrays rather oddly. It flattens them and doesn't account for indices.  For example, the following:
```
---
hosts:
- name: alpha
  ip: 192.168.0.1
- name: gold
  ip: 192.168.0.2
```
is currently parsed as:
```
/hosts/name: gold
/hosts/ip: 192.168.0.2
```

The last object of the array is the only one that's available from GetValues. However, I believe the intended interpretation of the above YAML is the following:

```
/hosts/0/name: alpha
/hosts/0/ip: 192.168.0.1
/hosts/1/name: gold
/hosts/1/ip: 192.168.0.2
```

Here array indices are interpreted as strings. This is in fact how confd parses arrays. Would you be open to change easykv's file backend to behave like confd's?

**Comment by HeavyHorst** [comment]
Sure, just send an PR and i'll happily merge it.

**Comment by andreykaipov** [comment]
Thank you will do! 😄

Encountered this while writing the tests for https://github.com/HeavyHorst/easykv/pull/7, so I'll finish that up after this issue.
